import type { ServiceCatalogItem } from "@/types";

export const serviceCatalog: ServiceCatalogItem[] = [
  {
    id: "svc-001",
    name: "Oil Change",
    description: "Engine oil replacement with oil filter",
    defaultPrice: 1500,
    category: "General Service",
    isActive: true,
  },
  {
    id: "svc-002",
    name: "Full Service",
    description: "Complete vehicle servicing including oil, filters, fluid checks",
    defaultPrice: 5000,
    category: "General Service",
    isActive: true,
  },
  {
    id: "svc-003",
    name: "Minor Service",
    description: "Basic service - oil change, filter replacement, fluid top-up",
    defaultPrice: 2800,
    category: "General Service",
    isActive: true,
  },
  {
    id: "svc-004",
    name: "Engine Tune-up",
    description: "Spark plug replacement, ignition system check",
    defaultPrice: 3500,
    category: "Engine",
    isActive: true,
  },
  {
    id: "svc-005",
    name: "Brake Pad Replacement",
    description: "Front & rear brake pad replacement",
    defaultPrice: 4500,
    category: "Brakes",
    isActive: true,
  },
  {
    id: "svc-006",
    name: "Brake Disc Resurfacing",
    description: "Brake disc machining for smooth braking",
    defaultPrice: 2200,
    category: "Brakes",
    isActive: true,
  },
  {
    id: "svc-007",
    name: "AC Gas Refill",
    description: "R134a refrigerant recharge for AC system",
    defaultPrice: 2500,
    category: "AC",
    isActive: true,
  },
  {
    id: "svc-008",
    name: "AC Compressor Repair",
    description: "AC compressor diagnosis and repair",
    defaultPrice: 8500,
    category: "AC",
    isActive: true,
  },
  {
    id: "svc-009",
    name: "Battery Replacement",
    description: "Car battery replacement with installation",
    defaultPrice: 5500,
    category: "Electrical",
    isActive: true,
  },
  {
    id: "svc-010",
    name: "Alternator Repair",
    description: "Alternator diagnosis and repair",
    defaultPrice: 6500,
    category: "Electrical",
    isActive: true,
  },
  {
    id: "svc-011",
    name: "Dent Repair",
    description: "Minor dent removal and panel beating",
    defaultPrice: 3000,
    category: "Body",
    isActive: true,
  },
  {
    id: "svc-012",
    name: "Paint Touch-up",
    description: "Scratch and chip paint repair",
    defaultPrice: 2000,
    category: "Body",
    isActive: true,
  },
  {
    id: "svc-013",
    name: "Tire Rotation",
    description: "Rotate all four tires for even wear",
    defaultPrice: 400,
    category: "Tires",
    isActive: true,
  },
  {
    id: "svc-014",
    name: "Wheel Alignment",
    description: "Four-wheel alignment and balancing",
    defaultPrice: 1200,
    category: "Tires",
    isActive: true,
  },
  {
    id: "svc-015",
    name: "Tire Replacement",
    description: "Tire replacement (per tire, excluding tire cost)",
    defaultPrice: 300,
    category: "Tires",
    isActive: true,
  },
];
