import type { User } from "@/types";

export const staff: User[] = [
  {
    id: "usr-001",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@garagecrm.in",
    phone: "+91-9876543210",
    role: "ADMIN",
    branchId: "br-001",
    isActive: true,
  },
  {
    id: "usr-002",
    name: "Priya Sharma",
    email: "priya.sharma@garagecrm.in",
    phone: "+91-9876543211",
    role: "ADMIN",
    branchId: "br-001",
    isActive: true,
  },
  {
    id: "usr-003",
    name: "Suresh Reddy",
    email: "suresh.reddy@garagecrm.in",
    phone: "+91-9876543212",
    role: "MANAGER",
    branchId: "br-001",
    isActive: true,
  },
  {
    id: "usr-004",
    name: "Anitha Nair",
    email: "anitha.nair@garagecrm.in",
    phone: "+91-9876543213",
    role: "RECEPTIONIST",
    branchId: "br-001",
    isActive: true,
  },
  {
    id: "usr-005",
    name: "Vikram Singh",
    email: "vikram.singh@garagecrm.in",
    phone: "+91-9876543214",
    role: "RECEPTIONIST",
    branchId: "br-002",
    isActive: true,
  },
  {
    id: "usr-006",
    name: "Murugan P",
    email: "murugan.p@garagecrm.in",
    phone: "+91-9876543215",
    role: "MECHANIC",
    branchId: "br-001",
    isActive: true,
  },
  {
    id: "usr-007",
    name: "Ramesh Gowda",
    email: "ramesh.gowda@garagecrm.in",
    phone: "+91-9876543216",
    role: "MECHANIC",
    branchId: "br-001",
    isActive: true,
  },
  {
    id: "usr-008",
    name: "Karthik Iyer",
    email: "karthik.iyer@garagecrm.in",
    phone: "+91-9876543217",
    role: "MECHANIC",
    branchId: "br-001",
    isActive: true,
  },
  {
    id: "usr-009",
    name: "Venkatesh M",
    email: "venkatesh.m@garagecrm.in",
    phone: "+91-9876543218",
    role: "MECHANIC",
    branchId: "br-002",
    isActive: true,
  },
  {
    id: "usr-010",
    name: "Prakash Rao",
    email: "prakash.rao@garagecrm.in",
    phone: "+91-9876543219",
    role: "MECHANIC",
    branchId: "br-002",
    isActive: true,
  },
];
